repos:
  - repo: local
    hooks:
      - id: check-pinned-dependencies
        name: Check that all dependencies are pinned
        entry: python scripts/check_pinned_deps.py
        language: system
        files: ^pyproject\.toml$
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: zuban
        name: zuban
        entry: zuban check
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfiles with hadolint
        language: docker_image
        types: ["dockerfile"]
        entry: hadolint/hadolint:v2.12.0 hadolint
