defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: anthropic_only
  - override /task@_global_: circle_packing
  - override /cluster@_global_: local
  - _self_

variant_suffix: "_anthropic"
