defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: small_budget
  - override /task@_global_: squeeze_hnsw
  - override /cluster@_global_: local
  - _self_

evo_config:
  num_generations: 50

variant_suffix: "_example"
